### ISSUE TITLE
Handling for `default` exports

### ISSUE THREAD

**Issue by igrayson** [rstuven/sinonquire#2]
Hi team,

I thought you'd find useful a survey we did for some mocking libraries. For sinonquire:
1. sinonquire autostubs classes (i.e., wraps `sinon.createStubInstance`) when `typeof require(‘foo’) == ‘function’)`. In babel (or, our configuration), `export default class Foo ..` produces `{ default: [Function] }`, which sinonquire doesn’t handle. I believe the example given on the sinonquire README doesn’t itself work, for this reason. The repo's tests use `module.exports = User` instead of ES6 class syntax given in the README.
2. sinonquire autostub behavior will miss (no wrapping), when we use convenience index.js redirects, like:

```
export Service from './Service';
export logger from './logger’;
```

In this example, `Service` is a class, and we need it to get wrapped by sinonquire in `sinon.createStubInstance`, which it _would_ do if we used `import Service from ‘./lib/Service’` (and if (1) was fixed), but it will not if we used `import { Service } from ‘./lib’`, which is what we do

**Comment by tachuris** [comment]
@igrayson Thanks for your comments. I've just released a version that should support both cases.
